name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "0 14 * * *" # every day at Melbourne midnight

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-mingw-w64-i686 \
            g++-mingw-w64-i686 \
            yasm \
            make \
            automake \
            autoconf \
            git \
            pkg-config \
            libtool-bin \
            nasm \
            gcc-mingw-w64-x86-64 \
            g++-mingw-w64-x86-64
      - name: Build ffmpeg
        run: sudo ./quick_build/quick_cross_compile_ffmpeg_fdk_aac_and_x264_using_packaged_mingw64.sh
      - name: List build result
        run : tree -h ./sandbox_quick/win64/quick_install/install_root/ffmpeg_simple_installed
